---
title: "Gastrointestinal III"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document
documentclass: article
classoption: a4paper
fontsize: 11pt
urlcolor: blue
---

# Main case

## Trigger 1

DDx: upper vs lower, stuff higher up => melaena

-  Haemorrhoids: varicose vein of perianal region
-  Colitis: ischaemic, inflamm, infn
-  CRC
-  IBD: ulcerative colitis + crohn's disease (less common for blood)
-  Trauma
-  AVM
-  Diverticulitis
-  Fissure
-  Polyps/FAP
-  Arterioenteric fistula
-  Peptic ulcer

Hx:

-  HPC: onset, frequency, anything worse/better, change in diet, 
    -  Info about poo: offensive odour (fat/mucous), consistency (liquid/solid), watery, colour, volume
    -  How frequent is blood
-  Associated symptoms: pain, nausea/vomiting, systemic weight loss, fatigue, bleeding/bruising
-  PMHx/PSHx
-  FHx
-  Social Hx

## Trigger 2

Constipation: usually haemorrhoids or anal fissure especially in 27M. 27M shouldn't really be anaemic. Even in F shouldn't just say "menstruation"

Types of diarrhoea: (todo: whip up a table for these types)

-  Osmotic: retention of water in the bowel from accumulation of non-absorbable substances
-  Secretory: electrolyte imbalance => water diffuses into stool. Often from inflamm
-  Motility: changed motility from hyperthyroidism, IBS, partial gastrectomy
-  Inflammatory: colon is inflamed, typically causes blood diarrhoea, e.g. IBD
-  (Malabsorptive: stool will float due to fats)


This pt: exudative (blood and mucus) + inflammatory. Not malabsorptive as his stool

Mucous in GIT: secreted for protection. Pus (secreted from inflamed). IBS and IBD

Associated pain to rectal bleeding:

-  Rectal: fissures
-  Abdominal:
    -  Severe: ischaemic colitis
    -  Mild to moderate: enteritis

Loperamide: opiod receptor agonist that doesn't cross BBB, decreasing activity of myenteric plexus


## Trigger 3

Hospital admission: think holistically, this pt is young adult male who has a partner who can look after him, chance that he'll have to go to hospital at night => yes

## Trigger 4

Bloods: urea elevated due to dehydration; albumin elevated due to chronic bleed; Hb due to anaemia, but MCV normal so probs not iron deficiency(?); CRP+WCC due to inflamm

Sigmoidoscopy: uses shorter instrument which can be done a lot faster

Todo: Copy a table between UC and CD from Don's thing

Natural Hx IBD: extraintestinal symptoms such as eyes, => complications such as toxic megacolon, 

Toxic megacolon: inflamm => dilation of bowel => increased permeability + perforation => $\Uparrow$ septic

Mx: principles start aggressive => less aggressive

-  Short term: steroids
-  Long term: immunosuppressants, resection for UC

## Trigger 5

IBD associated

-  Skin: psorosis
-  Jt: seroneg arthritis, ank spond
-  Liver: primary sclerosin cholangitis
-  Thromboses, metabolic bone diseases

Regular monitoring: if the disease is being managed, liver damage, females: pregnant and many drugs are teratogenic, common malignancy in immunosuppressed are skin, vaccines

# Short case 1

## Trigger 1

[Haemorrhoids](http://emedicine.medscape.com/article/775407-overview): *common* disease, varicose veins of perianal region. 
Causes = {pregnancy, constipation, obesity, portal hypertension, tumours}. 
Present: usually painless unless thrombosis, bleeding, "feel something when wiping". Rx: usually conservative (diet, stool softening), surgery: rubber band resection

-  Internal: above pectinate line, superior rectal
-  External: below pectinate line, inferior rectal, usually painful and usually thrombosed

Causes of GIT bleeding: split into upper, lower, anal (see: lecture 3)

## Trigger 2

Bowel cancer:

-  Left sided: constipation and is found earlier, blood on top of the poo (as poo has already formed)
-  Right sided: more liquidy so doesn't cause constipation, occult bleeding (blood mixed in)

Pain on defaecation: think haemorrhoids (thrombosed), anal fissure, anal polyps, abscesses, rectal ulcers, rectal cancer

[Laxatives](https://www.nps.org.au/australian-prescriber/articles/managing-constipation-in-adults):

-  Osmotic: indigestible carbohydrates => pass through => relative osmotic diarrhoea to soften stool
-  Bulking agents 
-  Stool softeners 
-  Stimulants
-  Lubricants

Diverticulosis: common, L in West, R in Asia, increases with age. 
Most are asymptomatic (70-80%), diverticular bleeding (outpouch with the vasa recta which is the weak part => bleeding not uncommon) (5-15%), diverticulitis (4%) = {simple (85%), complicated (15%)}

-  True: congenital, e.g. meckels
-  False: not all the layers, usually around vasa recta as that is the weakest, e.g. zenkers

## Trigger 3

Top *X* differentials, where $X=\in\mathbb{Z}$:

-  CRC: due to bleeding, and altered bowel habits
-  Diverticulitis/diverticulosis
-  Haemorrhoids

Explaining: emphasise importance and that it can cure things inside it

## Trigger 4

Further Ix:

-  Bloods: FBC (anaemia), ELFT, CRP/ESR, group+hold?, CEA (specific marker for Ca)
-  CT for staging

Risk factors for adenocarcinoma:

-  Smoking
-  Diet
-  Obesity
-  Genetic risk: FAP, lynch syndrome

Presentation: bleeding, abdo pain, tenesmus (feeling of incomplete emptying), anaemia (right), complete bowel obstruction, 

Screening: important because catching it early has high survival rates

# Short case 2

## Trigger 1

DDx:

-  CVS: ruptured AAA => ischaemia of bowel, vasculitis
-  Renal: UTI + symptoms of cephalexin, pyelonephritis
-  GIT: ischaemic bowel, perforation, ulcer, CRC, diverticulitis, anal fissure, haemorrhoids, fistula, abscess, infectious colitis (*C. difficile* because in nursing home; everyone would get it)
-  Genitourinary: pelvic inflamm disease

Compared to Trevor (IBD, CRC), she is Old F in nursing home on antibiotics: infectious colitides, CRC (less likely presentation as her thing is so acute), diverticulitis, ischaemic bowel

Mechanisms that antibiotics causing diarrhoea:

-  Inflammatory: *C. difficile* secrete toxins
-  Secretory: damage mucosa
-  Osmotic: disturb carbohydrate balance
-  Motility: increase gut motility

## Trigger 2

She's a vasculopath

*Triple whammy for renal failure: ACE, diuretic, NSAID (aspirin)*

Ex:

-  CVS: important to check JVP
-  GIT: 5 Fs 

## Trigger 3

Rigidity, guarding, rebound tenderness (pain after moving hand away after slowly palpating): suggests peritonitis/inflammation

Ix:

-  Bloods: FBC (anaemia), ELFT (kidney fn; she is on triple whammy for renal failure), ESR/CRP
-  ECG
-  Urine: urinalysis, dipstick
-  Stool: cultures (hard to grow *C. difficile*)
-  Imaging: CT (ischaemia less enhanced), angiograms
-  Colonoscopy

## Trigger 4

Ischaemic colitis (pain after eating; basically angina in GIT): global hypoperfusion => ischaemia. 
Can also be caused by strangulation, embolism, infn. 
Hers is an *acute on chronic* presentation. 

Ischaemic colitis: chronic issue, usually resolves on its own, Rx: bowel rest, broad spectrum IV antibiotics
Acute mesenteric colitis: medical emergency 
