---
title: "MSK I"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document
documentclass: article
classoption: a4paper
---

# Readings

## Describing a fracture

1.  Describe the film: who what when where why
2.  What type of fracture? Complete = {transverse, oblique, spiral, comminuted}, Incomplete = {bowing, bucle, greenstick}, Salter-Harris
3.  Where is fracture = {diaphysis, metaphysis, epiphysis}
4.  Is it displaced? {angulation, translation, rotation}
5.  Something else happening too?

## Trauma

### Primary survey

-  Circulation (including haemorrhage control)
-  Airway Maintenance (cervical spine control)
-  Breathing and Ventilation
-  Circulation (reassess again - this is IMPORTANT; check for pulses, bleeding, cyanosis,...)
-  Disability (check neurological status)
-  Exposure (undress patient completely - strip and flip, examining both sides of the patient) - cover as soon as practical to prevent hypothermia.

### Ix

-  FBC - Hb, Hct, Platelets
-  ABG with Lactate  - check for ventilatory failure and marker of shock (lactate)
-  Coag's - evidence of early trauma associated coagulopathy.
-  Blood alcohol
-  EUC
-  Group and Hold +/- X-Match as indicated. (Checks blood type)
-  ECG
-  CXR, PXR
-  eFAST (extended FAST ultrasound scan)
-  CT scans as indicated (generally in the obtunded major trauma patient a panscan is performed if the patient is haemodynamically stable)
-  Urinalysis

## Principles of fracture Mx

### Initial

Maintain/improve:

-  Blood supply
-  Soft tissue health

Open fractures

-  Prevent infn: antibiotics immediately
-  Allow fracture to heal
-  Restore fn in the limb

### Non-operative therapy

-  Casting: contraindicated if = {no displacement, displacement exists but not relevant to fn outcome, reduction impossible, reduction cannot be maintained, fracture produced by traction forces}
-  Traction = {skin, skeletal}

### Surgical therapy

-  Kirschner wires
-  Plates = {buttress, compression, neutralisation, tension-band, bridge} and screws
-  External fixation: used with open fractures that have significant soft tissue disruption

# CBL Main case

## Trigger 1

58M 2 story fall, injuries right leg and arm, denies head or neck injury.

Immediate Mx: primary survey (see above).

Further info from pt:

-  HPC: What caused him to fall such as seizure or slip? How did he fall? Land on anything? Remember the whole thing?
-  Site, onset, character, radiation, associations, time course, exacerbating/relieving factors, severity (in-depth HPC later).
-  See if anything else is wrong. Distracting injury could obfuscate.
-  Who is next of kin?

After primary survey => secondary survey

-  Head to toe Ex
-  Look for fractures
-  Pulses, sensation, pain: neurovascularly intact
-  Auscultate for breath sounds, heart sounds
-  Palpate
-  FAST ultrasound: see if there is something bleeding
-  Log roll to turn them over and look for same stuff
    -  Push down c-spine to check if there is any pain

## Trigger 2

Pt tachycardic when he came in and hypotensive. Pulse gone down for a bit probably due to morphine getting rid of pain.

Imaging indicated: X-rays of right upper and lower limb. Can be difficult to assess for spinal injuries so it might be alright to image spine.

## Trigger 3

Fractures:

-  Complete spiral fracture to distal diaphysis R tibia
-  Comminuted fracture proximal diaphysis R fibula
-  Compound comminuted (through the skin) middle diaphysis right ulna
    -  Note: have to be methodical because if the ulna is fucked then the radius could be too

Fracture Mx:

-  Non-operative: closed reduction (pulling the bone back into alignment)
-  Operative: open reduction

Complications from open fracture:

-  Infn
-  Embolism

## Trigger 4

DDx post-op pain: 5W's of post-op fever = {wind [pneumonia], water [UTI], wound [infns especially after day 5], wonderdrugs [iatrogenic], walking [walking reduces DVT]}

-  Compartment syndrome
-  DVT
-  Infn
-  Nerve palsy

On Ex for new leg pain:

-  Inspection: signs on inflammation, cyanosis
-  Palpate: neurovascular, loss/decrease pulses, temperature, cap refill (comparing both sides)
-  Neuro assessment

## Trigger 5

Compartment system features:

-  Parasthesia
-  Tenderness
-  Increased pain from passive stretching (e.g. toes)

# Short case 1

## Trigger 1

> 43F bilateral shin pain, worse on L. Worsening past 2-3/12. Back from 1/12 training deployment army involving vigorous training. 

Deep fibula N supplies anterior compartment of lower limb.

Pain origin: referred pain (sciatica can radiate to lower leg) [o/e could be no pain in the isolated area, but palpating the spine can demonstrate], dodgy gait, could be claudication, varicose veins, arthritis

To think of DDx: VINDICATE = {vascular, inflamm, neoplastic, degenerative/deficiency, idiopathic, congenital, autoimmune/allergic, traumatic, endocrine}

Questions to exclude red flags:

-  Have you been feeling tired and fatigued (Cancer)
-  Pain at rest or nocturnal, enough to disturb sleep
-  Weight loss, night sweats, or chills (Ca)
-  Hx of malignancy
-  Neuro compromise
-  Drugs or steroids (osteoporosis)
-  Immunosuppressed (infn; osteomyelitis)

Bone structure from exercise: Wolffs law, bones laid down where it is needed.

Hx questions:

-  HPC: SOCRATES, what do you think it is, why did you come in *today* as opposed to last week or yesterday,...
-  PMHx/PSHx
-  Medications (also gives indication for PMHx)/allergies/drugs
-  Fam Hx
-  Repro Hx
-  Social Hx: lifestyle, food, exercise, smoking

Menopause is a risk factor for osteoporosis.

MSK Ex: look $\rightarrow$ feel $\rightarrow$ move whilst comparing both sides

## Trigger 2

> Pain before deploying, has gradually worsened and now occurs with lighter exercise. Present at night.

Ex: Medial tibial stress syndrome has no swelling

Pathophysiology processes: fractures, necrosis

## Trigger 3

> Normal X-ray. She gets MRI

# Short case 2

## Trigger 1

> GP in Sarina (popn 6,000). Called by nurse working night shift. 72M brought in by *ambulance* found on bathroom floor. Couldn't get up, pain left hip, wife along.

Further info:

-  HPC: What caused him to fall such as seizure or slip? How did he fall? Land on anything? Remember the whole thing?
-  SOCRATES: site, onset, character, radiation, associations, time course, exacerbating/relieving factors, severity (in-depth HPC later).
-  Did you hit head
-  Remember everything, how did you fall?
-  See if anything else is wrong. Distracting injury could obfuscate.
-  Who is next of kin?
-  Social Hx to see how healthy he is

DDx: why can't pt get off ground

-  MSK: fracture, muscular issues
-  GIT: constipation
-  CVS: shock, MI, stroke
-  Resp:
-  Neuro: nerve palsy, parkinsons?, lots of pain
-  Depression? Drugs diuretics can make pt get up at night? Alcohol

DDx: hip pain

-  Extrinsic
    -  Abdo/pelvic causes = {appendicitis, ovarian pathology, bowel pathology, endometriosis}
    -  Local pathology such as inguinal/femoral herniae, lymph nodes
    -  Spinal or sacroiliac referred pain
    -  Meralgia paraesthetica (entrapment of lateral cutaneous nerve) or sciatica
    -  Malignancy
-  Intrinsic
    -  Soft tissue = {tendonitis, bursitis, snapping hip [movement of ITB over greater trochanter]}
    -  Joint = {osteoarthritis, rheumatoid, septic, synovitis}
    -  Bone = {hip/femur fracture, avascular necrosis}

Risk factors for falls in the elderly

-  MSK: muscle weakness, pain in feet
-  Neuro: balance, parkinsons, poor vision, inner ear pathology
-  CVS: hypotension
-  Renal: urinary incontinence can make people rush to the bathroom with increased risk of falling
-  External: clothes, external hazards, medications (polypharmacy)

## Trigger 2

> Found before 5am lying on floor, crying in pain, unable to get up. No PMHx of chest pain, palpitations, "fits, faints or funny turns" [pre-syncope/syncope?]. PMHx = {osteoarthritis, HTN, insomnia, hearing loss, BPH}. Meds = {atenolol [$\beta-1$ blocker; used for HTN], oxazepam [benzodiazepine; used for anxiety, insomnia, and alcohol withdrawal], panadol osteo [paracetamol; relief for osteoarthritis]}. Said he slipped on bath mat after waking up whilst going to the toilet. Falling $\rightarrow$ severe pain in left hip, felt unable to stand.

Specific physical Ex:

-  General inspection
-  Vitals
-  Cardio/resp Ex
-  Secondary survey?
-  Lower limb pulses

Hip Ex?

-  Inspect: deformities, swelling, scars, wasting
-  Posture: spinal, leg, foot
-  Gait: Trendelenburg sign or crossed adductor gait suggests advanced hip disease
-  Feel: swellings (herniae)
-  Move: flex, extend, int/ext rotate, ab/ad-duct
-  Fabre test: tries to reproduce pain to localise?
-  Impingement (fadir) test
    -  Ante: joint path, tendonitis, bursitis
    -  Post: sacroiliac or lumbar

Priorities: Mx severe pain in left hip and vitals. Urgent: probs not

PMHx and meds: osteoarthritis, HTN, atenolol, oxazepam (muscle relaxant)

## Trigger 3

> Man in pain. Given analgesia. Hypotensive, nil CVS/resp, no abnormalities other than left hip painful and limb appears shortened and externally rotated. Pedal pulses palpable bilaterally, sensation present bilaterally, dorsiflexion and plantar bilaterally. Too painful to proceed further. Hip X-ray ordered + FBC and eLFT. 2.5mg IV morphine, pt is kept nil by mouth(?)

Shortening

-  Proximal to trochanter: loss of articular cartilage from infn or arthritis, dislocation
-  Distal to trochanter: fractures of femur, tibia
-  Lengthening of one limb: increased vascularity stimulating growth (such as long bone fracture/neoplasia)

Mx priorities:

-  Pain
-  Fix fracture
-  Prevent fracturing again

Secondary survey: focused Hx and physical Ex. Assumed that life-threatening issues have been found and corrected. Includes Hx taking and vitals

Pt is at risk of hypovolaemia if it is bleeding.

Ix:

-  Imaging: X-ray to view what is happening
-  FBC: check for anaemia?
-  CHEM20
-  ECG
-  Group and hold
-  COAGs


## Trigger 4

> X-ray hip shows sub-capital fracture of the femur. Decreased bone density of the hip and femur. Normal biochemistry and haematology. Transferred to Mackay hospital where succesful surgery for fractured neck of femur. Bone mineral density scan confirms demineralisation of long bones and vertebrae with significant loss of trabeculae bone consistant with primary osteoporosis.

A pathologic fracture is a bone fracture caused by disease that led to weakness of the bone structure. E.g.osteoporosis, Ca, infn, inherited bone disorders,.... Fragility fracture $\in$ pathologic fracture, occurs as a result of normal activities such as fall from standing height or less.

Bone mineral density (looks at calcium):

-  $-2.5<\text{osteopaenia}\leq-1$
-  $\text{osteoporosis}\leq-2.5$

Osteoporosis Mx:

-  Pharmacologic: bisphosphanates (alendronate), calcitonin, denosumab (RANKL antag)
-  Vertebroplasty and kyphoplasty: for pt with persistent and severe focal back pain due to vertebral collapse
-  Dietary measures: adequate calcium and vit D, smoking and alcohol
-  Physical therapy: weight bearing exercise
-  Hormone therapy

Blood supply: avascular necrosis and non-union are common in fractures of the neck of femur (sub-capital) without surgical intervention, because the blood supply is interrupted. Rare after intertrochanteric fractures.

Prognosis: varied, but is complicated by advanced age, as hip fractures increase the risk of death and major morbidity in the elderly. QoL may be decreased due to mobility issues.

Safely discharged:
