---
title: "MSK II"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
  pdf_document
documentclass: article
classoption: a4paper
---

# Bone

## Physiology

-  Matrix composed of 35% osteoid (mainly type I collagen) and 65% mineral component (mainly hydroxyapatite).
-  2 types of matrix = {woven, lamellar}
-  Cells = {osteoblasts, osteoclasts, osteocytes}
-  Development:
    -  Long bones from endochondral ossification
    -  Flat bones from intramembranous ossification
-  Remodelling:
    -  RANKL: stimulates RANK $\rightarrow$ increased osteoclast differentiation (stimulated by PTH)
    -  OPG: inhibits RANKL RANK signalling $\rightarrow$ decreased osteoclast differentiation


## Pathology

### Congenital

-  Dysostoses: defects in migration and condensation of mesenchyme
-  Dysplasia: global disorganisation of bone/cartilage
    -  Achondroplasia: most common AD disorder from g.o.f *FGFR3* mutation $\rightarrow$ retarded cartilage growth
    -  Thanatophoric dysplasia: lethal dwarfism also g.o.f *FGFR3*
    -  Osteogenesis imperfecta: mutation in *type I collagen* $\rightarrow$ dominant negative lof mutation $\rightarrow$ too little bone $\rightarrow$ fragility
    -  Osteopetrosis: reduced bone resorption resulting from impaired formation or fn of osteoclasts. AR mutations in *CA2* or *TCIRG1*

### Metabolic

-  Osteopenia
-  Osteoporosis: age related, reduced physical activity, genetic factors, calcium nutritional state, hormonal influences (e.g. estrogen deficiency).  
Clinical course can lead to lordosis/kyphoscoliosis/PE/pneumonia.
-  Rickets and osteomalacia: manifestations of vit D deficiency or abnormal metabolism

### Paget's

Paget disease is condition of increased but disordered and structurally unsound bone. Both genetic and environmental causes (usually *SQSTM1*). Hallmark is mosaic pattern of lamellar bone.

1.  Initial osteolytic stage
2.  Mixed osteoclastic/osteoblastic stage $\rightarrow$ predominance of osteoblastic activity
3.  Burned out quiescent osteosclerotic phase

### Fracture healing

-  Rupture of vessles results in haematoma surrounding area of bone injury
-  Clotted blood provides fibrin mesh, sealing off fracture site, and providing scaffold for inflamm cells/fibroblasts/angiogenesis.
-  Degradnulated platelets and inflamm cells release PDGF, TGF-$\beta$, FGF to activate osteoprogenitor cells.
-  End of first week: mass of uncalcified tissue called *soft callus* provides anchorage between ends of fractured bone.
-  After two weeks: soft callus $\rightarrow$ bony callus due to deposition of woven bone, hyaline/fibro-cartilage, and endochondral ossification.

### Osteomyelitis

Inflamm of bone and marrow, usually secondary to infn.  

-  Pyogenic: usually bacteria, rarely fungi. Normally *Staph aureus*
    1.  Haematogenous spread
    2.  Extension from contiguous site
    3.  Direct implantation after compound fractures
-  Mycobacterial osteomyelitis

### Bone tumours

| Category          | Behavior  | Tumor Type                    | Common Locations                           | Age (yr) | Morphology                                                                                               |
|-------------------|-----------|-------------------------------|--------------------------------------------|----------|----------------------------------------------------------------------------------------------------------|
| Cartilage forming | Benign    | Osteochondroma                | Metaphysis of long bones                   | 10–30    | Bony excrescence with cartilage cap                                                                      |
| —                 | —         | Chondroma                     | Small bones of hands and feet              | 30–50    | Circumscribed hyaline cartilage nodule in medulla                                                        |
| —                 | Malignant | Chondrosarcoma (conventional) | Pelvis, shoulder                           | 40–60    | Extends from medulla through cortex into soft tissue, chondrocytes with increased cellularity and atypia |
| Bone forming      | Benign    | Osteoid osteoma               | Metaphysis of long bones                   | 10–20    | Cortical, interlacing microtrabeculae of woven bone                                                      |
| —                 | —         | Osteoblastoma                 | Vertebral column                           | 10–20    | Posterior elements of vertebra, histology similar to osteoid osteoma                                     |
| —                 | Malignant | Osteosarcoma                  | Metaphysis of distal femur, proximal tibia | 10–20    | Extends from medulla to lift periosteum, malignant cells producing woven bone                            |
| Unknown origin    | Benign    | Giant cell tumor              | Epiphysis of long bones                    | 20–40    | Destroys medulla and cortex, sheets of osteoclasts                                                       |
| —                 | —         | Aneurysmal bone cyst          | Proximal tibia, distal femur, vertebra     | 10–20    | Vertebral body, hemorrhagic spaces separated by cellular, fibrous septae                                 |
| —                 | Malignant | Ewing sarcoma                 | Diaphysis of long bones                    | 10–20    | Sheets of primitive small round cells                                                                    |

## Joints

-  Solid (nonsynovial: synarthroses): structural integrity
    -  Fibrous synarthroses: cranial structures and bonds between roots of teeth and jawbone
    -  Cartilaginous synarthroses (synchondroses): symphyses between sternum and ribs
-  Cavitated (synovial joints): have joint space for wide range of movement. Lined by type A synoviocytes (specialised macros with phago activity) and type B synoviocytes (sim to fibroblasts and synthesise hyaluronic acid). Hyaline cartilage serves as elastic shock absorber.

### Arthritis

-  Osteoarthritis: degeneration of articular cartilage leading to structural and fn failure of synovial joints.
-  Rheumatoid arthritis: chronic inflamm of autoimmune origin attacking the joints
-  Juvenile idiopathic arthritis: affects before age 16
-  Seronegative spondylarthropathies:
    -  Absence of rheumatoid factor
    -  Path changes in ligamentous attachments rather than synovium
    -  Involvement of sacroiliac joints $\pm$ others
    -  Association with HLA-B27
    -  Bony proliferation leading to ankylosis
-  Infectious arthritis
-  Suppurative arthritis: bacterial infns that cause acute suppurative usually enter joints from distant sites by haematogenous spread. Restricted ROM
-  Lyme disease: systemic infn by *Borella burgdorferi*
-  Crystal induced arthritis:
    -  Gout: urate crystal deposition in/around joints.
    -   Calcium Pyrophosphate Crystal Deposition Disease (Pseudogout)

### Tumours

Primary are rare.

-  Ganglion and Synovial Cysts: small (1–1.5 cm) cyst that is almost always located near a joint capsule or tendon sheath.
-  Tenosynovial Giant Cell Tumor

## Soft tissue tumours

Soft tissue refers to non-epithelial tissue excluding the skeleton, joints, central nervous system, hematopoietic and lymphoid tissues

### Tumours of adipose tissue

-  Lipoma: benign
-  Liposarcoma: malignant

### Fibrous tumours

-  Nodular fasciitis: self limiting fibroblastic and myofibroblastic proliferation occuring in upper extremities of young adults
-  Superificial fibromatosis: infiltrative proliferation causing local deformity but has innocuous clinical course
-  Deep fibromatosis: desmoid tumours. Large infiltrative masses that recur frequently but do not metastasise.

### Sk muscle tumours

-  Rhabdomyosarcoma: malignant mesenchymal tumour with sk muscle differentiation. Three main subtypes are recognized: alveolar [fusions of FOXO1 to PAX3/PAX7] (20%), embryonal (60%), and pleomorphic (20%).

### Smooth muscle tumour

-  Leiomyoma: benign most common in the uterus but can arise in any soft tissue site.
-  Leiomyosarcoma: They occur in adults and affect women more frequently than men.

### Tumours of uncertain origin

-  Synovial sarcoma
-  Undifferentiated pleomorphic sarcoma: includes malignant mesenchymal tumors with high-grade, pleomorphic cells that cannot be classified into another category by a combination of histomorphology, immunophenotype, ultrastructure, and genetics.

# Main case

## Trigger 1

> GP suburban, 32F, wrist pains over last few weeks, started after netball, R>L and right hand dominant

Pathophysiological processes: VINDICATE

-  Vascular: infarction
-  Inflammation/infn: RA, reiters syndrome (after $\Delta$sex Hx especially: males; hurts to pee, can't see, hurt my knee), crystal arthropathies, lyme disease, septic arthritis, viral arthralgia
-  Degenerative: OA (could be secondary), RSI, carpal tunnel syndrome (nerve entrapment) 
-  Iatrogenic: drugs (hydrolazine)
-  Congenital: osteogenesis imperfecta
-  Autoimmune: RA, SLE
-  Trauma: overuse injury, trauma [did you fall weirdly?]
-  Endocrine:

Arthritis (inflamm) vs arthralgia (pain in jts)

-  Mono: 1
-  Oligo: 2-4
-  Poly: $\geq5$

Things masquerading as joint pain: muscle, nerve

Imp systemic symptoms for DDx: fever (timecourse, associated with other symptoms), malaise (might suggest high metabolic demand; chronic inflamm)

-  HPC: SOCRATES + have you had before + impacting on daily life, have you been sick recently, did you fall?
-  Systems review:
    -  CVS: palpitations, chest pain
    -  Neuro: fits, faints, funny, numbness, headaches, vision/hearing
    -  Resp: SOB goes with CVS
    -  GIT: nausea/vomiting, changes in bowel habit
    -  Genito/urinary: frequency/pain/bleeding on urination, women = menstrual Hx
-  PMHx, sexual Hx, FHx + SHx + travel Hx
-  Any neurological symptoms?
-  Any skin changes/rashes
-  Red flags: Waking at night? Constant pain or does it ever go away? Fevers?
-  Pt says they feel tired: are you always tired? Sleeping well? Did it come on same time as pain? Can you remember when you last fell well? (is better than "how long have you been feeling tired")
-  Drugs/medications/smoking
-  Social Hx

## Trigger 2

> Feeling very tired for few months, dull ache worse in mornings, has not woken at night, full time secretary 2 young kids, no relevant PMHx, FHX: 55 aunt has some sort of arthritis, systems review unremarkable, no other jt problems

Pathophysiological process between fatigue and joint pain: infn $\Uparrow$metabolic demand, pain can be taxing and have to compensate, think of cytokines for inflamm as they can cause fatigue. 

Autoimmune diseases: $\text{genetic}\times\text{environment}$

## Trigger 3

> Inflammation around prox interphalangeal joints of 2, 3, 4.

Mechanical vs inflamm: 

-  Mechanical: just painful when moving it, gets worse as using it during the day, wouldn't expect systemic symptom from a knee abrasion
-  Inflamm: movement makes better, morning stiffness, systemic symptoms, 

Ix:

-  Bloods: FBC to check white cells, CHEM20 to check for liver fn because viruses (EBV, RRV), CRP, RA factor, CCP (citric citrulinated peptide)
-  Imaging: X-ray

## Trigger 4

> Ix results

According to criteria she'd have 6 points $\rightarrow$ definite RA

Natural Hx: progressive deformities of jt, 10% increased risk of CVS mortality within 10 years of Dx (inflamm $\rightarrow$ vasculitis/athero)

## Trigger 5

Biological agents: counteract body 

# Short case 1

## Trigger 1

> Michael Lee 24M back pain 4 years worse in the morning

Anatomical structures:

-  Tendons, ligaments, muscles
-  Nerves, spinal cord
-  Kidneys: stones/cyst
-  Repro stuff iff female

Questions to ask

-  PC: SOCRATES: have you had any bladder weakness (neuro question)?

## Trigger 2

> Pain gets better on exercise. 

Types of back pain

| Type | Character | Time course | Radiation | NSAID response | Onset | Age |
| ------ |---------------  | ---------- | --------- | ------- |  ------ | ----- |
| Mechanical | Thinking muscular: diffuse/achey | Worse with movement PM AM | Lumbar to back of thigh | Moderate/good | Post trauma/gradual | Mid-late |
| Inflammation | Something pushing: stabbing | AM more likely than PM | To the butt | Really good | Insidious/gradual | 20s |
| Radicular | Sharp/stabbing | Worse with activity | Goes down the leg towards ankle and foot | Limited | Usually sudden | Any |
| Neuropathic | Burning | Constant, no association with activity | Towards ankle and foot | Limited | Insidious |
| Malignant | Deep gnawing contionuous ache | Constant, wakes up at night | Limited | Insidious |

## Trigger 3

What are the types of spondyloarthropathies (Rheumatoid factor negative)

-  Ankylosing spondylitis: $M>F$,
-  Psoriatic arthritis: nail pitting, sausage fingers
-  Reactive arthritis: after an infn (think UTIs, STIs), $M>F$
-  IBD associated: 
-  
-  

Range of symptoms (don't forget extra-articular symptoms):

-  Oseopenia
-  LOTS of CVS issues

## Trigger 5

Natural Hx:

-  Inflamm of tendons (such as calcaneal tendon)
-  Oedema
-  Ossification
-  Fusion of spine $\rightarrow$ bamboo spine

Treatment:

-  Pain management: NSAIDs
-  Physiotherapy: also helps manage pain whilst preventing fusion

Effects:

-  Depression
-  Affect work: maybe think about re-skilling

# Short case 2

## Trigger 1

DDx for mono-articular pain: 

-  Gout: first MTP joint
-  Septic arthritis: one large joint
-  Trauma
-  Osteoarthritis: knee/hips (weight bearing)
-  RA: little joints
-  Psoriatic arthritis
-  Bleeding into the joints: haemophilia
-  Bite

Other Qs to ask

-  Skin conditions: psoriatic
-  Fever/inf: septic arthritis

Ex:

-  General inspection: how she looks, gait, how she is walking
-  Look: inflammed
-  Touch
-  Move
-  Maybe CVS and look at peripheral pulses

## Trigger 2

Pathophysiology of gout:

-  Hyperuricaemia: underexcretion (90%) or overproduction (10%)
-  Excess urate $\rightarrow$ crystalisation $\rightarrow$ inflamm $\rightarrow$ phago of crystals $\rightarrow$ inflamm: joints get affected
-  Can clear up in a couple of days


Risk factors

-  M
-  Obesity
-  Kidney disease

Diagnostic finding in pt with gout: urate crystals

## Trigger 3

Mx of gout:

-  Acute
    -  NSAIDs
    -  Prednisone
    -  Colchicine for acute gout: interrupts cycle of mono-Na crystal deposition. Stops the inflammatory reaction to the crystals. 
-  Chronic
    -  Lower urate to $<0.36\text{mmol/L}$
    -  Lifestyle modifications: low purine diet, low sugar (fructose $\rightarrow$ hyperuricaemia), stay hydrated
    -  Allopurinol: inhibits xanthine oxidase $\rightarrow$ inhibits urate production. Not really given during acute flare up because it *may* exacerbates. 

Synovial fluid in following disorders:

-  Normal: clear straw like colour
-  Septic arthritis: elevated WCC, culture positive, purulent exudate
-  Crystal deposition disease: see crystals, elevated WCC, negative culture, high urate/Ca
-  RA: elevated WCC, sterile, normal urate, neutrophil predominance
-  OA: joint mice 

## Trigger 4

Long term gout damage:

-  Joint damage
-  Recurrent gout: deposits
-  Skin nodules
-  Extra-articular damage: 
    -  Kidney injuries/stones
    -  HTN
    -  Hypercholesterolaemia/hyperuricaemia

Mx in this pt:

-  Check medications, maybe can't use the thiazide
-  Lifestyle mentioned above

