---
title: "MSK III"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document
documentclass: article
classoption: a4paper
urlcolor: blue
---

# Readings

# Common paediatric hip diseases in primary care

## Developmental dysplasia of the hip (DDH)

Most common in F firstborn infants. Inherited polygenic, acetabulum is shallow, and may contain pulvinar or fat.

Tests are Ortolani, Barlow, or Galeazzi signs.

## Slipped capital femoral epiphysis (SCFE)

Displacment of the capital femoral epiphysis from the rest of the femur through the cartilaginous growth plate known nas proximal femoral physis. Occurs  due to forces + acetabulum holding femoral head in place. This has sig proactive surgical methods to prevent severe hip arthritis. Risk factors = {obesity, male, african-american, pacific islander, endocrine disorders}

## Legg-Calve-Perthes disease

-  Synovitis (couple of weeks): reduced ROM
-  Osteonecrosis (6-12/12): contour of femoral head is maintained but part of it becomes ischaemic
-  Fragmentation phase (up to 3 years): pain, limping, reduced ROM
-  Revascularisation and regeneration (1-3 years): resorption of necrotic bone and dev of new bone. Permanent deformity can occur here.

# General approach to MSK

-  Inspection: SEADS = {swelling, erythema, atrophy, deformity, scars}
-  Palpation
-  ROM
-  Neurovascular status

## Treatment

-  Modification of activities
-  Ice
-  Compression
-  Elevation

# Main case

## Trigger 1

> 32M, crossfit 4/12, sudden sharp pain in groin

DDx groin pain: 

-  CVS: avascular necrosis, 
-  Resp: 
-  MSK: muscle strain, tendonitis, trochanteric bursitis, overuse injury, fracture, labral tear, ligamentous injury, 
-  GIT: bowel obstruction
-  Neuro: nerve impingement
-  Genitourinary: kidney stones, testicular torsion, ovarian cyst
-  Lymphadenopathy, cellulitis

Anatomical structures referring pain: knee, back, hip, intraabdominal = {repro, kidneys}

Questions to ask: also about shooting/numbness/sharp or stabbing/...

## Trigger 2

Catching = joint, giving way under him = ligamentous

[RACGP article on hip pain](http://www.racgp.org.au/afp/2014/april/hip-pain-in-young-adults/)

## Trigger 3

If worried about adductor pain: can use adductor squeeze. 

Imaging:

-  X-ray: only see bone
-  CT: loads of radiation
-  Ultrasound:
-  MRI: lots of soft tissue, fractures

## Trigger 4

Ix:

-  Bloods: FBC, 
-  More imaging

Hip impingement:

-  CAM lesion: non-smooth (aspherical) femoral head: 14% in normal population.
-  Pincer: non-smooth acetabulum
-  Combined: both CAM and pincer

Prognosis:

-  Increased risk of OA

## Trigger 5

Arthrogram: injection of contrast followed by MRI. Allows intraarticular structures such as cartilage to be found. Risks = {anaphylaxis, infn, hitting a nerve}. Doubles sensitivity compared to normal MRI without arthrogram (0.60). 

Labral tears are common, often asymptomatic. 

Mx:

-  Rest
-  NSAIDs
-  Activity modification
-  Physiotherapy exercises
-  Arthroscopy
-  Debridement of bone

## Trigger 6

Physio exercises

# Short case 1

## Trigger 1

Knee structures

-  Bones: patella, tibia, fibula, femur
-  Soft tissue: tendons, menisci, ligaments

Contact sport: ACL (cruciates: snap and then "ow" | non-contact change in direction), lateral collateral ligament, med meniscus

Questions:

-  HPC
-  Did you hit your head? Remember a snap/something? How exactly did you fall? Allergies?

Bucket list for knee pain

-  Acute: trauma
-  Chronic: knee pain without trauma

## Trigger 2

Ligaments responding to stress

-  Special tests may give *false negatives* straight away

## Trigger 3

Effusion: in a joint space | potential space

Oedema: outside a joint

Mx of ACL injury: (rupture/tear)

-  Initial: RICE = {rest, ice, compression, elevation}
-  Non-operative: physio, balance
-  Operative: surgical repair

# Short case 2

## Trigger 1

How are hips checked: 

-  Barlow: can dislocate the hip
-  Ortolani: pull it out

Galeazzi test: look at height of knee

## Trigger 2

## Trigger 3

Tx of DDH:

-  Van Rosen splint: QLD + Scandinavia
-  Pavlik harness
-  If instability at 10 years then surgery

## Trigger 4

Leg length discrepancy: dislocation (moves posteriorly and shortening)

-  SUFE: 10-16
-  Perthes: 4-10

