---
title: "MSK IV"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document
documentclass: article
classoption: a4paper
urlcolor: blue
---

# Readings

## Cancers

Described as a dull and aching pain in the location. Worse at night and sometimes increases with activity. Common symptoms also fever and night sweats. Many pt do not have any symptoms but notice a painless mass. 

Primaries:

1.  Multiple myeloma: tumour of bone marrow.
2.  Osteosarcoma: most common in teenagers and children. Found femur, tibia, hip, shoulder.
3.  Ewings sarcoma: age between 5-20. Common locations are upper and lower leg, pelvis, upper arm, ribs. 
4.  Chondrosarcoma: 40-70 years of age. Found hip, pelvis, shoulder. 

Common sites for secondaries: breast, lung, thyroid, renal, prostate

# Path POW

## Arthritis

If the PIP extended and DIP flexed: swan neck deformity

| OA | RA | Both |
| ------------ | ----------- | ----------- |
| Minimal joint inflammation | Morning joint stiffness lasts >1 hour | Affects small joints of the hands |
| Joint pain worsens after use | Presence of extra-articular manifestations  | Visible nodules on hands |
| | Abnormal levels of autoantibodies  | | 
| | Mostly symmetrical polyarthritis affecting young females | |

Radiological

-  Both: loss of jt space, malalignment of joints
-  OA: subchondral cysts and sclerosis, formation of bony outgrowths at the end of joints

# Main case

# Short case 1

## Trigger 1

Ulcer: local defect of tissue or organ caused by sloughing of inflammatory or necrotic material.

Pathogenesis of ulcer formation: possibly from kicking the bed, then repetitive trauma. 

Factors preventing ulcer from healing (learn this):

-  Infn
-  Smoking
-  *Old* age
-  Heavy alcohol consumption
-  Medication: steroids, NSAIDs
-  Obesity
-  Repetitive trauma
-  Diabetic: due to decreased blood flow, increased risk for infn due to high sugar, neuropathy
-  Vascular disease (oxygen supply)
-  Poor hygiene + improper wound care
-  Malnutrition
-  Super rare genetic diseases

Wound present for long time: 

-  Can affect gait/joints
-  Osteomyelitis
-  Scar
-  Could turn malignant (if wound not healing, always biopsy it)

## Trigger 2

Kids more likely for acute osteomyelitis (haematogenous route) whereas adults more likely for chronic (direct). 

Imaging to see osteomyelitis:

-  Xray: 2 weeks after infn
-  MRI: a couple of days

Questions to ask for a possible primary cause:

-  Any claudication
-  Check for diabetes
-  General inspection for malnutrition

## Trigger 3

Most common cause for osteomyelitis: *Staph*, *Pseudomonas* is stinky and common in diabetics, 

-  Haematogenous: staph and influenza B (common in kids)
-  Open fractures: staph e coli
-  Spinal: staph, strep, e coli, IV drug users = candida
-  Diabetes/PVD: polymicrobial

Pathogenesis:

-  Infection
-  Inflammatory response
-  Phagocytosis attempt to contain infection by liberating enzymes
-  Enzymes lyse the bone
-  Pus forms
-  Pus travels through Haversian system
-  Increased intraosseous pressure
-  End arteritis and impaired blood flow
-  Ishaemic necrosis of bone
-  Pus breaks through cortex
-  Abscess
-  Subperiosteal infection
-  Elevated periosteum (involucrum) 
-  Rupture of periosteum(cloacae)


# Short case 2

## Trigger 1

Common causes of shoulder pain:

-  Glenohumeral
    -  RC muscles
    -  Bursae
    -  Tendons
    -  Adhesive capsulitis
    -  Labrum
    -  Synovium
    -  Articular cartilage
    -  Articular bone surface
-  Extraglenohumeral
    -  MSK: OA common in AC joint, diaphragmatic irritation
    -  CVS: MI
    -  C spine
    -  Malignancy: pancoast tumour (Horner's syndrome)
    -  Herpes
    -  PE
    -  Depression
    -  Polymyalgia

DDx: also RA, malignancy, tendinopathy (-itis), 

Questions: Any particular movements that hurt? Have you started doing anything new recently? Do an ECG.

## Trigger 2

Hx indicative of pathology: probably acute, maybe traumatic 

Overhead work: puts pressure on RC muscles

Abducting arms:

-  10-20: supraspinatus
-  20-90: deltoids
-  90+: levator scapulae

Smoking and shoulder pain:

-  Decreased bone density
-  Tendinopathy
-  Risk factor for RC tears

## Trigger 3

If glenohumeral cause then even passive ROM should be tender. 

Natural Hx of RC injury: little evidence for spontaneous repair. Once damaged a bit there is the same amount of force subjected to the same tendon so increased predisposition to further damage. 

Natural Hx of RC injury: little evidence for spontaneous repair. Once damaged a bit there is the same amount of force subjected to the same tendon so increased predisposition to further damage. 

Natural Hx of RC injury: little evidence for spontaneous repair. Once damaged a bit there is the same amount of force subjected to the same tendon so increased predisposition to further damage.

Risk factors for RC tendinopathy

-  Extrinsic: overhead repeated use, prior injuries, problems in one shoulder can affect the other, anything decreasing ability to heal
-  Intrinsic: shoulder laxity/instability, smoking, Ca, old age

Imaging necessary: not really. Unless red flags, fractures, super old age then don't need to image. 

## Trigger 4


