---
title: "Neuro V"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document
documentclass: article
classoption: a4paper
urlcolor: blue
---

# Readings

# Main case

## Trigger 1

Symptoms due to old age: unilateral, stiff and weak, only 60 so probs not. Age related degeneration is typically bilateral, older,...

CNS

-  Motor power
-  Movement
-  Coordination: cerebellum

DDx:

-  Neuro: stroke, parkinsons, huntingtons, MS, GBS, MND (motor neuron disease), myasthenia gravis, cerebellar alcohol, vertigo, essential tremor, visual impairment that is not being picked up, dementia, peripheral neuropathy
-  Malig: primary or secondary tumours

Sensory for coordination:

-  Propioception
-  Visual
-  Vestibular apparatus

Hx taking:

-  Flesh out PC
    -  Onset: how did symptoms come in
    -  Fumbling at rest or moving
    -  Dizziness/falling over: vertigo, inner ear
    -  Visual fn: reading or not
    -  Headaches/faints: tumours
-  Anything else
-  PMHx
-  PSHx
-  FHx
-  Sexual Hx
-  Medications, allergies, adverse drugs
-  Social Hx: smoking, drinking, drugs, rest of it, how is it affecting life, dependents

## Trigger 2

Key symptoms

-  Slowing up: bradykinesia
-  Tremor: increases when trying to hurry or agitated
-  Mumbling
-  Episode of vertigo in the past: stemetil

Parkinsons: bradykesia, rigidity, tremor, postural instability

Basal ganglia: disinhibition and inhibition of differnet planned movements. Therefore has issues starting a movement. 

| Extrapyramidal             | Corticospinal             | Cerebellar           |
|----------------------------|---------------------------|----------------------|
| Parkinsonism               | Increased tendon reflexes | Intention tremor     |
| Dystonia                   | Fasiculations             | Troubles with speech |
| Restlessness, urge to move | Increased tone            |                      |
| Gait: shuffling            |                           |                      |
| Lack of normal arm swing   |                           |                      |
| Walking heel to toe        |                           |                      |
| Cogwheel rigidity          |                           |                      |

## Trigger 3

Parkinsons: loss of 60-80 of dopaminergic neurons in pars compacta

Extrapyramidal disorders: anything disrupting the pathway. Lesions in basal ganglia, drugs

## Trigger 4

Side effects of levodopa:

-  Arrhythmias
-  Hypotension
-  Nausea
-  GI bleeding
-  Hallucinations
-  End of dose deterioration of fn
-  Oscillations
-  Dyskinesea

There are no disease modifying agents for parkinsons. These drugs only cure symptoms for a bit, disease will still progress.

## Trigger 5

On/off symptoms: try reduce dose but give more frequently so it still has effects without adverse effects

Natural Hx: loss of motor fn, dementia, death, autonomic effects


# Short case 1

## Trigger 1
  
> 53M weakness and clumsiness of right hand 3/12. 6/12 began dropping things with R hand, gradual deterioration in handwriting, losing grip strength.

Anatomical sites (DDx for muscle weakness; unilateral/focal tends to be neurological))

-  Muscles:
    -  Primary myopathies: hereditary/congenital (dystrophies), finalmm, metabolic
    -  Secondary myopathies: infn (trichanosis), conn tissue disease, thyroid/adrenal dysfn, paraneoplastic, drugs
    -  Trauma
-  NMJ: *myasthenia gravis*, lambert eaten, toxins such as snake venoms/ticks/pesticides
-  LMN: peripheral nerve entrapment, polyneuropathy, GBS, *post-polio syndrome* (in sufferers of polio), *multifocal motor neuropathy*
-  Spinal cord: *spinal cord compression* (radiculopathy from spinal stenosis), neoplasms, stuff damaging peripheral nerve roots, infn from CMV/lyme can damage anterior horn => LMN damage, *MS*, 
-  UMN: tumour
-  Cerebral hemisphere: CVA (usually +sensory)
-  Neurodegenerative diseases like *motor neuron diseases (MND)* = {amyotrophic lateral sclerosis (ALS), primary lateral sclerosis (PLS), hereditary spastic paraparesis (HSP), spinal muscular atrophy (SMA), x-linked spinobulbar muscular atrophy (SBMA)}
-  Systemic: *Vit B12 deficiency*, hypercalcaemia/hyperparathyroidism (+abd pain, excessive urination, renal stones), depression, *heavy metal poisoning*, *lyme disease*


Hx:

-  HPC
    -  Tell me more...
    -  What does weakness mean? Sometimes pt confuse weakness with fatigue, often part of systemic disorders, psych, MS, parkinsons. Pt might describe rigidity/incoordination as weakness, ask "what could you do that you no longer can" fishing for "lifting up milk",...
        -  Fatigue describes the inability to continue performing a task after multiple repetitions
        -  Primary weakness is unable to perform the first repetition of the task
        -  Asthenia is a sense of weariness or exhaustion in the absence of muscle weakness. Common in people who have chronic fatigue syndrome, sleep disorders, depression, or chronic heart, lung, and kidney disease
    -  Site
    -  Onset: insidious onset suggests degenerative or chronic (metabolic ,hereditary), intermittent (e.g. using it makes it worse suggests myasthenia gravis), particular positions making it bad then mechanical issue such as entrapment neuropathy, radiculopathy, localised vascular occlusion, particular times of day suggests ion channel disorder, random symptom timing with quick recovery suggests transient ischaemia of CNS
    -  Character, radiation
    -  Associated symptoms: 
        -  Atrophy/fasciculations suggest LMN
        -  Systemic symptoms (probs not unilateral arm) can be from endocrine (thyroid, diabetus)
        -  Neoplasias/infn
        -  *Sensory* such as parasthaesia, vision, vertigo suggests NS
        -  Change in character of voice, problems swallowing (pharyngeal muscles)
        -  Increased urinary urgency can suggest spinal damage (myelopathy)
    -  How is it affecting daily life, what does he think it is?
-  PMHx: can get clues for infn cause or neoplastic
-  SHx
-  FHx
-  Medications (amiodarone, chemotherapeutic agents, interferon, cocaine, corticosteroids, penicilin, sulfonamides, statins, NSAIDS), allergies, ADR
-  Social Hx: drugs, alcohol, cigarettes

## Trigger 2

Cues:

-  Generally weak: something systemic, or just feeling shit
-  No sensory or paraesthesia: do exam first, but suggests against radiculopathies
-  No head, neck, or shoulder pain
-  No recent injuries: against trauma
-  No pattern to weakness, not aware of stuff that makes it better or worse: probably not mechanical/orthopaedic such as nerve entrapment
-  No fatigueable element: less likely NMJ
-  No bladder or bowel disturbances, no double vision
-  No difficulties with swallowing or changes to voice/speech: less likely cranial nerves involved
    -  CN V: muscles for mandible, tensor veli palatini
    -  CN VII: motor muscles of facial expression + stapedius, sensory ante $\frac{2}{3}$ tongue
    -  CN IX: motor middle pharyngeal constrictor + stylopharyngeus, sensory post $\frac{1}{3}$ tongue, velum, tonsils
    -  CN X: motor majority of viscera, sends motor commands to pharyngeal constrictors, cricothyroid for changes in pitch, glossopalatine and levator veli palatine muscles
    -  CN XI: trapezius and SCM of the neck
    -  CN XII: motor controlling tongue movement (intrinsic + extrinsic). Lesions here can result in fasciculations.
-  PMHx relatively uneventful: no post-polio

Ex clinical signs:

-  
-  Neuro upper limb

Clin findings suggestive of MND

-  Asymm weakness in upper or lower limbs
-  Brisk reflexes in wasted limb
-  Weakness in absence of pain or prominent sensory symptoms
-  Relentless progression of symptoms and signs

## Trigger 3

https://i.imgur.com/fUq88Wh.png <!-- image to be knit into the doc, under images/ -->

| Dx                    | Positives                   | Negatives                   |
|-----------------------|-----------------------------|-----------------------------|
| Peripheral neuropathy | Explains weakness           | Hyperreflexia               |
| Cervical cord lesion  |                             | Nothing below the level     |
| Muscular dystrophy    | Explains bilateral weakness | Reflexes increased, PAINFUL |
| R ulnar nerve lesion  | Weakness R hand             | Doesn't explain bilateral   |
| Motor neuron disease  | Vague as fuck               |                             |


MND: often Dx of exclusion. Generally occurs when age $\in[30,60]$, with degeneration of ante horn cells in spinal cord, motor nuclei of lower cranial nerves, and corticospinal/bulbar pathways. Usually sporadic, some familial. 5 varieties based on clinical grounds:

1.  Progressive bulbar palsy: bulbar involvement predominates owing to disease processes affecting primarily the motor nuclei of the cranial nerves
2.  Pseudobulbar Palsy: bilateral corticobulbar disease reflecting UMN dysfn. "Pseudo-bulbar effect" with uncontrollable laughing/crying to stimuli
3.  Progressive spinal muscular atrophy: LMN deficit in limbs due to degen of ante horn cells
4.  Primary lateral sclerosis: purely UMN deficit in the limbs
5.  Amyotrophic lateral sclerosis: mix of U and LMN in the limbs, sometimes associated with cognitive decline (frontotemporal dementia), psudobulbar effect, or parkinsonism

Differences between bulbar and pseudobulbar palsy (signs and symptoms):

-  Bulbar: LMN lesion to cranial nerves IX, X, XI, XII, in the medulla or lesons of the lower cranial nerves outside the brainstem. Symptoms = {tremulous lips, tongue weak and wasted and fasculations, drooling + dysphagia (unable to swallow), dysphonia, articulation issues (cant pronounce *r*)}
-  Pseudobulbar: lesion to corticobulbar tracts. Bilateral damage must be present as many muscles have bilateral innervation. Presentation = {paralysed tongue and no fasciculations, dribbling, facial muscles paralysed, exaggerated reflexes, dysphonia, dysphagia, emotional lability may be present}

Further Ix

-  Electromyography: may show changes of chronic partial denervation, ab~N spontaneous activity in resting muscle. Dx should not be made with confidence unless change are found in $\geq3# spinal regions, or $2$ regions + bulbar 
-  Motor conduction velocity is usually normal
-  Sensory conduction studies normal
-  Biopsy of wasted muscle
-  Serum CK may be elevated, but not as high as muscular dystrophies
-  CSF normal

What are possible future complications

-  Sialorrhoea: unintentional loss of saliva through the mouth
    -  Choking
    -  Pneumonia
-  Dermatological: rashes
-  Resp failure
-  Death

Principles of Mx for MND

-  Refer
-  Admit for initiation or titration of noninvasive ventilation for those with low inspiratory pressure, may prolong survival
-  Riluzole: reduces presynaptic release of Glu, increases short term survival for ALS
-  Symptomatic/supportive measures: trials of anticholinergics
    -  Braces/walker
    -  Physical therapy to prevent contractures
    -  Mx saliva
    -  Dyspnoea
    -  Constipation
    -  Muscle cramps/spasms/spasticity
    -  Depression, emotional lability
    -  Choking sensation
    -  Panic claustrophobia
-  Relieve pseudobulbar affect with combination dextromethorphan/quinidine
-  Gastronomy tube if dysphagia is severe
-  Palliative

## References

-  [Good DDx for weakness](http://www.dartmouth.edu/~dons/part_2/chapter_12.html)
-  [AFP article: evaluation of pt with muscle weakness](http://www.aafp.org/afp/2005/0401/p1327.html)
-  [Medscape MND](http://emedicine.medscape.com/article/2111360-overview#a1)
-  [AFP article of MND](http://www.racgp.org.au/download/documents/AFP/2011/December/201112zoing.pdf)
-  [Categories of MND](http://accessmedicine.mhmedical.com.ezproxy.library.uq.edu.au/content.aspx?sectionid=135716257&bookid=1843&jumpsectionID=135717169&Resultclick=2)

# Short case 2
