---
title: "Neuro IV"
author: "Aaron Khoo"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  pdf_document
documentclass: article
classoption: a4paper
urlcolor: blue
---

# POW

Presentation: 30F left lag dragging, difficulties walking long distances, feels tingling in hands and it seems to have come back.

Ix: HLA-DR2 haplotype associated with MS, oligoclonal bands in CSF suggest inflamm process, normal metabolic panel and thyroid excludes other explanations such as hypothyroidism.

Explanation of oligclonal bands: each band represents IgG produced by activated B cell. These result in the autoimmune attacks. Being present in CSF but NOT plasma means it originates in CNS. If was in blood, then systemic immune response could have crossed leaky BBB into CSF. 

Pathophysiology: Multiple sclerosis is an example of a Type IV hypersensitivity. Initially, T cells cross the blood brain barrier and attach to ligands on the myelin sheath and oligodendrocytes . The T cells mistake these cells as being foreign and release cytokines, resulting in inflammation that damages the myelin. Normally, myelin increases the speed of electrical signals via saltatory conduction. When the myelin is gone, the signals can’t propagate along the axons as well. This can eventually lead to conduction block . Hence, we see the neurological deficits in this patient. At first, through the process of remyelination some of the symptoms will resolve. However, as time goes on, this process is less effective and symptoms get worse.

Histo: fried egg looking cells are oligodendrocytes.

| Symptom       | Site of damage                                                      |
|---------------|---------------------------------------------------------------------|
| Blurry vision | Optic nerve                                                         |
| Double vision | Oculomotor nerve                                                    |
| Limb weakness | Pyramidal tract                                                     |
| Limb numbness | Posterior columne medial lemniscus pathway  (fine touch and propio) |
| Ataxia        | Cerebellum                                                          |

# Main case

## Trigger 1

Causes of irritability: high pitched cries

-  VINDICATE for the DDx

Parent Hx

-  Good Hx: associated Sx (vomiting, diarrhoea,...)
-  Outbreaks at the daycare
-  Any complications during birth (obstetric Hx)
-  Developmental Hx
-  How does Mad act usually?
-  How has her feeding changed
-  Nappy change rate
-  Rash?
-  Sleep habit change
-  Activity/interactivity level
-  Family Hx/sickness/who is living at home?

Assessment:

-  Paediatric assessment triangle
-  Primary survey (ABCDE)
-  Secondary survey
-  Ongoing assessment

## Trigger 2

Mx plan: address "what's wrong with her": you've brought her in early, but too early to figure out exact cause. Make sure to come back if it gets worse, come back even if not for vaccinations. Have to really figure out how the parents feel.

## Trigger 3

Physical signs

-  Poor cap refill in child

Meningitis: causes Hib, Neisseria, Strep

Under 3/12 & fever: send to ED

$\text{Septic screen} = \text{urine}+\text{bloods (FBC)}+\text{blood cultures} \pm \text{LP} \pm \text{xray (if resp symptoms)}$

Meningitis:

|                   | Viral                      | Bacterial                                                            |   |   |
|-------------------|----------------------------|----------------------------------------------------------------------|---|---|
| Clinical symptoms | Headaches, increased ICP,… | Viral + confusion (much worse, progressesfaster as bacteria has pus) |   |   |
| Rate              | Way more common            | Less common                                                          |   |   |
| CSF               |                            |                                                                      |   |   |
|                   |                            |                                                                      |   |   |

Pathophysiology:

1.  Inflammation
2.  Infn => ventricles
3.  Necrosis, impaired CSF flow, CNS fn

Increases permeability of BBB

Strep pneumoniae is most common cause of MOPS = {meningitis, otitis media, pneumonia, sinusitis}

| Test                       | Bacterial                 | Viral                        |
|----------------------------|---------------------------|------------------------------|
| Opening pressure           | Elevated                  | Usually normal               |
| White blood cell count     | $\geq1000\text{ per }mm^{3}$| <100 per mm3            |  
| Cell differential          | Predominance of PMNs      | Predominance of lymphocytes |
| Protein                    | Mild to marked elevation  | Normal to elevated           |
| CSF-to-serum glucose ratio | Normal to marked decrease | Usually normal               |

## Trigger 4

Risk with LP: removal of CSF can suck brain through foramen magnum (coning)

# Short case 1

## Trigger 1

One eye: probably not occipital lobe as at optic chiasm, left optic tract gets info from both eyes (left visual field), sim for right.

Questions to ask:

-  Fam Hx
-  What was she doing at the time?
-  Any headaches when she does move her eye?
-  Associated symptoms: numbness, tingling, incontinence?
-  Nature of pain
-  Better or worse
-  Onset: there all day?
-  Allergies, drugs


## Trigger 2

Ex for pupilliary reflex

-  Direct
-  Consensual

## Trigger 3

Optic neuritis: inflammed myelin sheaths of optic nerve.
85% of cases permanent damage to optic nerve.
Tx: steroids for severe or chronic cases.

## Trigger 4

Causes of demyelinating disease: autoimmune, Vit B12, 

Dx for MS: McDonald criteria: 2 diff lesions in 2 diff places and 2 diff times

# Short case 2

## Trigger 1

Peripheral nerves is site.

Breathless: up to 30% of GBS require ventilation.

## Trigger 2

Main cause is campylobacter causing GIT infns. 
Bacteria have LPS which are similar to myelin gangliocytes => creating molecular mimicry. 
Early lymphocytic infiltrates than macrophage mediated stripping of myelin. 
Segmental demyelination then infiltrates. 
Most repair normally. 


| Mnemonic    | UMN                                 | LMN           |
|-------------|-------------------------------------|---------------|
| Strength    | $\Downarrow$                        | $\Downarrow$  |
| Tone        | $\Uparrow$                          | $\Downarrow$  |
| Others      | Superficial reflexes. Absent clonus | Fasiculations |
| Reflexes    | $\Uparrow$                          | $\Downarrow$  |
| Muscle mass | $\sim N$                            | $\Downarrow$  |
| Babinski    | $(+)$                               | $(-)$         |

Mx:

-  Plasmaphoresis or Ig but NOT both
-  20% mortality if ventilated
-  Long term complications DVT, paralysis, death, peripheral neuropathy
-  Recovery takes a *long* time: 6/12 to *years*
